<?php

namespace ContainerSezLBb6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaylistsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PlaylistsController' shared autowired service.
     *
     * @return \App\Controller\PlaylistsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PlaylistsController.php';

        $container->services['App\\Controller\\PlaylistsController'] = $instance = new \App\Controller\PlaylistsController(($container->privates['App\\Repository\\PlaylistRepository'] ?? $container->load('getPlaylistRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->privates['App\\Repository\\FormationRepository'] ?? $container->load('getFormationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\PlaylistsController', $container));

        return $instance;
    }
}
