<?php

namespace ContainerSezLBb6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaylistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8rewS3E.App\Entity\Playlist' shared service.
     *
     * @return \App\Entity\Playlist
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8rewS3E": it references class "App\\Entity\\Playlist" but no such service exists.');
    }
}
