<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNjdhPJf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNjdhPJf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNjdhPJf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNjdhPJf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNjdhPJf\App_KernelDevDebugContainer([
    'container.build_hash' => 'NjdhPJf',
    'container.build_id' => '21413e5e',
    'container.build_time' => 1717570426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNjdhPJf');
